/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedOperacionalRouteImport } from './routes/_authenticated/operacional'
import { Route as AuthenticatedExtensaoRouteImport } from './routes/_authenticated/extensao'
import { Route as AuthenticatedDesktopRouteImport } from './routes/_authenticated/desktop'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksEncerrarOciosasRouteImport } from './routes/api/public/hooks/encerrar-ociosas'
import { Route as ApiPublicHooksAgregarDiarioRouteImport } from './routes/api/public/hooks/agregar-diario'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacionalRoute =
  AuthenticatedOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtensaoRoute = AuthenticatedExtensaoRouteImport.update({
  id: '/extensao',
  path: '/extensao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesktopRoute = AuthenticatedDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksEncerrarOciosasRoute =
  ApiPublicHooksEncerrarOciosasRouteImport.update({
    id: '/api/public/hooks/encerrar-ociosas',
    path: '/api/public/hooks/encerrar-ociosas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgregarDiarioRoute =
  ApiPublicHooksAgregarDiarioRouteImport.update({
    id: '/api/public/hooks/agregar-diario',
    path: '/api/public/hooks/agregar-diario',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/desktop': typeof AuthenticatedDesktopRoute
  '/extensao': typeof AuthenticatedExtensaoRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/api/public/hooks/agregar-diario': typeof ApiPublicHooksAgregarDiarioRoute
  '/api/public/hooks/encerrar-ociosas': typeof ApiPublicHooksEncerrarOciosasRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/desktop': typeof AuthenticatedDesktopRoute
  '/extensao': typeof AuthenticatedExtensaoRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/agregar-diario': typeof ApiPublicHooksAgregarDiarioRoute
  '/api/public/hooks/encerrar-ociosas': typeof ApiPublicHooksEncerrarOciosasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/desktop': typeof AuthenticatedDesktopRoute
  '/_authenticated/extensao': typeof AuthenticatedExtensaoRoute
  '/_authenticated/operacional': typeof AuthenticatedOperacionalRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/agregar-diario': typeof ApiPublicHooksAgregarDiarioRoute
  '/api/public/hooks/encerrar-ociosas': typeof ApiPublicHooksEncerrarOciosasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/aprovacoes'
    | '/atividades'
    | '/change-password'
    | '/desktop'
    | '/extensao'
    | '/operacional'
    | '/ranking'
    | '/relatorios'
    | '/api/public/hooks/agregar-diario'
    | '/api/public/hooks/encerrar-ociosas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/aprovacoes'
    | '/atividades'
    | '/change-password'
    | '/desktop'
    | '/extensao'
    | '/operacional'
    | '/ranking'
    | '/relatorios'
    | '/'
    | '/api/public/hooks/agregar-diario'
    | '/api/public/hooks/encerrar-ociosas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/atividades'
    | '/_authenticated/change-password'
    | '/_authenticated/desktop'
    | '/_authenticated/extensao'
    | '/_authenticated/operacional'
    | '/_authenticated/ranking'
    | '/_authenticated/relatorios'
    | '/_authenticated/'
    | '/api/public/hooks/agregar-diario'
    | '/api/public/hooks/encerrar-ociosas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAgregarDiarioRoute: typeof ApiPublicHooksAgregarDiarioRoute
  ApiPublicHooksEncerrarOciosasRoute: typeof ApiPublicHooksEncerrarOciosasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional': {
      id: '/_authenticated/operacional'
      path: '/operacional'
      fullPath: '/operacional'
      preLoaderRoute: typeof AuthenticatedOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extensao': {
      id: '/_authenticated/extensao'
      path: '/extensao'
      fullPath: '/extensao'
      preLoaderRoute: typeof AuthenticatedExtensaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desktop': {
      id: '/_authenticated/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof AuthenticatedDesktopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/encerrar-ociosas': {
      id: '/api/public/hooks/encerrar-ociosas'
      path: '/api/public/hooks/encerrar-ociosas'
      fullPath: '/api/public/hooks/encerrar-ociosas'
      preLoaderRoute: typeof ApiPublicHooksEncerrarOciosasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agregar-diario': {
      id: '/api/public/hooks/agregar-diario'
      path: '/api/public/hooks/agregar-diario'
      fullPath: '/api/public/hooks/agregar-diario'
      preLoaderRoute: typeof ApiPublicHooksAgregarDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDesktopRoute: typeof AuthenticatedDesktopRoute
  AuthenticatedExtensaoRoute: typeof AuthenticatedExtensaoRoute
  AuthenticatedOperacionalRoute: typeof AuthenticatedOperacionalRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDesktopRoute: AuthenticatedDesktopRoute,
  AuthenticatedExtensaoRoute: AuthenticatedExtensaoRoute,
  AuthenticatedOperacionalRoute: AuthenticatedOperacionalRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAgregarDiarioRoute: ApiPublicHooksAgregarDiarioRoute,
  ApiPublicHooksEncerrarOciosasRoute: ApiPublicHooksEncerrarOciosasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
